#!/bin/bash

# Quick Start Guide for Testing Authentication System
# This script helps you test the signup and login workflow

echo "======================================"
echo "StageScout Auth System - Test Guide"
echo "======================================"
echo ""

# Check if running from correct directory
if [ ! -d "be" ] || [ ! -d "fe" ]; then
    echo "❌ Error: Please run this script from the stagescout root directory"
    exit 1
fi

echo "📋 TESTING THE SIGNUP & LOGIN SYSTEM"
echo ""
echo "1. START THE BACKEND SERVER"
echo "   - Open Terminal 1"
echo "   - Run: cd be && python -m uvicorn app.main:app --reload --host 0.0.0.0 --port 8000"
echo "   - Backend will be available at: http://localhost:8000"
echo "   - API docs at: http://localhost:8000/docs"
echo ""

echo "2. START THE FRONTEND SERVER"
echo "   - Open Terminal 2"
echo "   - Run: cd fe && npm run dev"
echo "   - Frontend will be available at: http://localhost:5173"
echo ""

echo "3. TEST THE SIGNUP WORKFLOW"
echo "   - Open http://localhost:5173 in your browser"
echo "   - Click 'Sign In' button (top right)"
echo "   - Click 'Sign Up' link at the bottom of login modal"
echo "   - Fill in the form with valid data:"
echo ""
echo "   📝 Test Signup Data:"
echo "   - Full Name: Test User"
echo "   - Email: testuser@example.com"
echo "   - Phone: 5551234567"
echo "   - Password: TestPass123!"
echo "   - Confirm: TestPass123!"
echo "   - Security Q1: Answer any question"
echo "   - Security Q2: Answer any question"
echo ""

echo "4. PASSWORD STRENGTH TEST"
echo "   While entering password, watch the strength meter:"
echo ""
echo "   ✅ Valid Examples:"
echo "      - SecurePass123!"
echo "      - MyP@ssw0rd"
echo "      - Complex#Pass456"
echo ""
echo "   ❌ Invalid Examples (watch feedback):"
echo "      - short (too short)"
echo "      - nouppercase123! (no uppercase)"
echo "      - NOLOWERCASE123! (no lowercase)"
echo "      - NoNumbers! (no numbers)"
echo "      - NoSpecial123 (no special char)"
echo ""

echo "5. ERROR SCENARIO TESTING"
echo ""
echo "   Test Case 1: Duplicate Email"
echo "   - Try signing up with same email twice"
echo "   - Should see: 'Email already registered'"
echo ""
echo "   Test Case 2: Invalid Email"
echo "   - Try: 'notanemail' or '@example.com'"
echo "   - Should see: 'Invalid email format'"
echo ""
echo "   Test Case 3: Weak Password"
echo "   - Try: 'weak123' (too short, no special char)"
echo "   - Watch strength meter show red"
echo ""
echo "   Test Case 4: Mismatched Passwords"
echo "   - Enter different values in password fields"
echo "   - Confirm button should be disabled"
echo ""

echo "6. LOGIN TEST"
echo "   After successful signup:"
echo "   - You should be logged in automatically"
echo "   - Refresh page, should still be logged in (cookie persisted)"
echo "   - Click user menu (top right) and logout"
echo "   - Click Sign In again"
echo "   - Enter your email and password"
echo "   - Should login successfully"
echo ""

echo "7. BACKEND API TESTING"
echo "   Open: http://localhost:8000/docs"
echo ""
echo "   Try these endpoints directly:"
echo ""
echo "   a) Check all users:"
echo "   - GET /api/test-users"
echo ""
echo "   b) Signup new user:"
echo "   - POST /api/auth/signup"
echo "   - Body: {\"email\": \"api@test.com\", \"password\": \"ApiTest123!\", ...}"
echo ""
echo "   c) Login:"
echo "   - POST /api/auth/login"
echo "   - Body: {\"email\": \"your@email.com\", \"password\": \"YourPass123!\"}"
echo ""
echo "   d) Get current user:"
echo "   - GET /api/auth/me"
echo ""

echo "8. BROWSER DEVELOPER TOOLS"
echo "   - Open DevTools (F12)"
echo "   - Go to Application > Cookies"
echo "   - Look for 'access_token' cookie"
echo "   - Check HttpOnly and Secure flags"
echo ""

echo "9. COMMON ISSUES & FIXES"
echo ""
echo "   ❌ Backend won't start:"
echo "   - Check: pip install -r requirements.txt"
echo "   - Verify port 8000 is not in use"
echo ""
echo "   ❌ Frontend won't connect to backend:"
echo "   - Check CORS settings in be/app/main.py"
echo "   - Verify backend is running on port 8000"
echo ""
echo "   ❌ Cookies not saving:"
echo "   - Check browser cookie settings"
echo "   - Verify CORS 'allow_credentials' is True"
echo ""
echo "   ❌ Password validation not working:"
echo "   - Ensure all special characters are entered"
echo "   - Watch the strength meter for guidance"
echo ""

echo "======================================"
echo "✅ System Ready for Testing!"
echo "======================================"
echo ""
echo "Next Steps:"
echo "1. Open two terminals"
echo "2. Start backend: cd be && python -m uvicorn app.main:app --reload"
echo "3. Start frontend: cd fe && npm run dev"
echo "4. Visit http://localhost:5173"
echo "5. Click Sign In and test the signup flow!"
echo ""
